# templates/networkpolicy.yaml
{{- if .Values.enableNetworkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "murmur.fullname" . }}-ice-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "murmur.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "murmur-rest.selectorLabels" . | nindent 12 }}
    ports:
    - protocol: TCP
      port: 6502
{{- end }}

---
# values.yaml
enableNetworkPolicy: true
---------------------------------------------
# File: templates/networkpolicy.yaml

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.networkPolicy.name }}
  namespace: {{ .Values.networkPolicy.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.networkPolicy.podSelector.matchLabels.app }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.networkPolicy.ingress.from.podSelector.matchLabels.app }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.ingress.ports.port }}


## File: values.yaml

networkPolicy:
  name: murmur-ice-access
  namespace: opr-develop
  podSelector:
    matchLabels:
      app: murmur
  ingress:
    from:
      podSelector:
        matchLabels:
          app: murmur-rest
    ports:
      port: 6502


--------------------------------------worked
# File: templates/networkpolicy.yaml

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.networkPolicy.name }}
  namespace: {{ .Values.networkPolicy.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.networkPolicy.podSelector.matchLabels.app }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.networkPolicy.ingress.from.podSelector.matchLabels.app }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.ingress.ports.port }}

## values
networkPolicy:
  name: murmur-ice-access
  podSelector:
    matchLabels:
      app: murmur
  ingress:
    from:
      podSelector:
        matchLabels:
          app: murmur-rest
    ports:
      port: 6502
